import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Organized sidebar for the Next.js TS Tailwind Supabase Starter documentation
 */
const sidebars: SidebarsConfig = {
  start: [
    'intro',
    'structure',
    {
      type: 'category',
      label: 'Features',
      items: ['features/authentication', 'features/database'],
    },
    {
      type: 'category',
      label: 'Development Guide',
      items: [
        'development/blueprint',
        'development/testing',
        'development/deployment',
        {
          type: 'category',
          label: 'Tools',
          items: [
            {
              type: 'autogenerated',
              dirName: 'tools',
            },
          ],
        },
        {
          type: 'category',
          label: 'Prompts',
          items: [
            {
              type: 'autogenerated',
              dirName: 'prompts',
            },
          ],
        },
        'development/contributing',
        'development/version-reference',
      ],
    },
  ],
  components: [
    {
      type: 'category',
      label: 'Layout',
      items: [
        {
          type: 'autogenerated',
          dirName: 'components/layout',
        },
      ],
    },
    {
      type: 'category',
      label: 'Navigation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'components/navigation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Basic UI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'components/ui',
        },
      ],
    },
    {
      type: 'category',
      label: 'Forms',
      items: [
        {
          type: 'autogenerated',
          dirName: 'components/forms',
        },
      ],
    },
    'components/typography',
  ],
};

export default sidebars;
